### ISSUE TITLE
Show AirsDayOfWeek property throws exception when value is not a weekday

### ISSUE THREAD

**Issue by miguedevel** [Vannevelj/TVDBSharp#19]
For example the show with ID 370444 returns this JSON:
```
"overview": "A horror anthology series based on urban legends that takes viewers deeper into the horrors that lurk just beneath the surface of America.",
    "lastUpdated": 1587973965,
    "airsDayOfWeek": "Weekdays",
```
which can't be parsed to System.DayOfWeek so an exception is thrown on GetShow().
The exception message: {"Error converting value \"Weekdays\" to type 'System.Nullable`1[System.DayOfWeek]'. Path 'data.airsDayOfWeek', line 1, position 590."}

**Comment by Vannevelj** [comment]
Hey @miguedevel , thanks for alerting me of this. I've submitted an updated nuget package to the store and it should be available to you in the next 10-15 minutes: https://www.nuget.org/packages/TVDBSharp/4.0.0

I've marked it as a breaking change because I've added my own enum for `DayOfWeek` that also supports "Weekdays" as a value. I appreciate you taking the time to write this up!
